### ISSUE TITLE
flamegraph fails on Github Workflows CI

### ISSUE THREAD

**Issue by mabbamOG** [flamegraph-rs/flamegraph#117]
pretty much what the title says. attempting to run `cargo flamegraph` in a Github Ubuntu Workflow machine fails with a huge amount of output to the console.
To set it up, i used something similar to:

```yaml
- name: Setup Cargo Install
  uses: actions-rs/install@v0.1
  with:
    crate: flamegraph
    version: latest
    use-tool-cache: true
- name: Run flamegraph profiler 
  run: cargo flamegraph --bin my_binary --root 
```
