### ISSUE TITLE
Unknown in svg image (Rust)

### ISSUE THREAD

**Issue by nricciardi** [flamegraph-rs/flamegraph#329]
I'm trying to profile my Rust project, but when I run flamegraph and then open `flamegraph.svg` I don't see function name, instead I see `[unknown]`.

How can I fix?

![flamegraph](https://github.com/flamegraph-rs/flamegraph/assets/64961208/e3d77803-0069-4ca0-9a42-df81292abc6a)

**Comment by djc** [comment]
What OS are you on? What debug info have you configured for the Cargo profile you're profiling against?

**Comment by nricciardi** [comment]
I'm on Linux Mint 21.3 (kernel: 5.15.0-113-generic).

Following my `Cargo.toml` file:

```toml
[package]
...

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.5"
build_html = "2.4.0"
clap = "4.4.18"
env_logger = "0.10.1"
image = "0.24.8"
log = "0.4.20"
notify = "6.1.1"
oxipng = { version = "9.1.1", features = ["parallel"]}
rayon = "1.8.0"
regex = "1.10.2"
reqwest = { version = "0.11.24", features = ["blocking"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.31"
simple_logger = "4.3.3"
thiserror = "1.0.50"
url = "2.5.0"

[profile.release]
debug = true
```
