### ISSUE TITLE
SVG report doesn't contain my Rust functions

### ISSUE THREAD

**Issue by nricciardi** [flamegraph-rs/flamegraph#330]
I'm using Flamegraph on Linux Mint 21.3 (kernel 5.15.0-113-generic) to profile my Rust application. When I run

```
cargo flamegraph -- [my args]
```

the terminal remains blocked showing:

```
[ perf record: Woken up 82 times to write data ]
[ perf record: Captured and wrote 22,570 MB perf.data (1421 samples) ]
```

(SVG file is not produced)

I must interrupt with CTRL + C and then SVG report is produced, but it does **not** have any profiled function of my Rust application.

If I run flamegraph with the same application, but throwing e.g. `todo!()`, then terminal exits correctly and flamegraph produces SVG report without CTRL + C.

My `Cargo.toml` file is the following:

```toml
[dependencies]
anyhow = "1.0.75"
base64 = "0.21.5"
build_html = "2.4.0"
clap = "4.4.18"
env_logger = "0.10.1"
image = "0.24.8"
log = "0.4.20"
notify = "6.1.1"
oxipng = { version = "9.1.1", features = ["parallel"]}
rayon = "1.8.0"
regex = "1.10.2"
reqwest = { version = "0.11.24", features = ["blocking"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.31"
simple_logger = "4.3.3"
thiserror = "1.0.50"
url = "2.5.0"

[profile.release]
debug = true
```  

I have tried also using `--root` option without results. **How can I fix it?**
